site_name: Kareem Marzouk
nav:
  - Home: index.md
  - Background: background.md
theme:
  name: material
  favicon: assets/favicon.svg
  icon:
    logo: fontawesome/brands/space-awesome
  palette:
    scheme: slate
    primary: custom
  font:
    texr: Roboto Mono
    code: Roboto Mono
extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/neoteroi-timeline.css
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bkmarzouk/
    - icon: fontawesome/brands/github
      link: https://www.github.com/bkmarzouk/
plugins:
  - search
markdown_extensions:
  - neoteroi.timeline
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
